import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Header from '@/app/components/includes/header';
import Footer from '@/app/components/includes/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body 
        className={`
          ${inter.className} 
          mx-auto 
          max-w-7xl 
          px-2 
          sm:px-6 
          lg:px-8
        `}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
};